spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financeAppDB
    username: admin
    password: admin

  jpa:
    show-sql: true

  server:
    servlet:
      session:
        cookie:
          secure: false

app:
  cors:
    allowed-origins: http://localhost:5173