spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  session:
    jdbc:
      cleanup-cron: "0 0 6 * * *"

server:
  tomcat:
    threads:
      max: 10
  servlet:
    session:
      cookie:
        secure: true

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGIN}